FROM debian:latest
USER root
RUN \
    apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -f install -y --no-install-recommends \
    htop \
    unzip \
    locate \
    p7zip-full \
    vim \
RUN \
    gem install nokogiri 

RUN \
    apt-get install -y \
    python3-pip \
    python3-dev &&\
    cd /usr/local/bin &&\
    ln -s /usr/bin/python3 python &&\
    pip3 install --upgrade pip


RUN \
    wget -q https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz -O go.tar.gz && \
    tar -C /usr/local -xzf go.tar.gz && \
# Install node
    curl -sL https://deb.nodesource.com/setup_14.x | bash && \
    apt install -y nodejs
# Install Perl 
ENV GOROOT "/usr/local/go"
ENV GOPATH "/root/go"
ENV PATH "$PATH:$GOPATH/bin:$GOROOT/bin"

#Working Directory of tools
RUN \
    cd /home/$USER &&\
    mkdir tool-for-pentester &&\
    cd tool-for-pentester

